apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  labels:
    name: result-app-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: result-app-pod
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod   # service pod u bu labeldan yakalar
    spec:
      containers:
      - name: result-app
        image: abdullah1606/phonebook-result
        ports:
        - containerPort: 80
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-admin-password
        envFrom: 
          - configMapRef:
              name: servers-configmap
#       env:
#        - name: MYSQL_USER
#          value: "clarus"
#        - name: MYSQL_PASSWORD
#          value: "Clarsuway_1"              
#        - name: MYSQL_DATABASE
#          value: "phonebook"      
#        - name: MYSQL_DATABASE_HOST
#          value: "mysql-service.default.svc.cluster.local"   bu mysql servisin adi, default namespace adi.
#Eger bir RDS olsaydi onun entrypoint olcakti value kismina!!!   