apiVersion: v1
kind: Secret
metadata: 
    name: mysql-secret
type: Opaque
data: 
    mysql-root-password: UjEyMzRy
    mysql-admin-password: Q2xhcnVzd2F5XzE=

#echo -n "R1234r" | base64
#echo -n "Clarsuway_1" | base64