apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  labels:
    name: mysql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysql-pod
  template:
    metadata:
      name: mysql-pod
      labels:
        name: mysql-pod   # Service bu pod u yakalicak. Servslerler podlari yakalr deploymentlari degil
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        imagePullPolicy: Always # lokale bakar yoksa pull eder image i. Never deseydin sadece lokale bakar yoksa bir sey yapmaz.
        ports:
        - containerPort: 3306
        env: 
        - name: MYSQL_PASSWORD 
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-admin-password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: mysql-root-password
        envFrom: 
        - configMapRef:
            name: database-configmap
        volumeMounts: 
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
#        env:
#        - name: MYSQL_ROOT_PASSWORD
#          value: "R1234r"
#        - name: MYSQL_USER
#          value: "clarus"
#        - name: MYSQL_PASSWORD
#          value: "Clarusway_1"
#        - name: MYSQL_DATABASE
#          value: "phonebook"