apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    name: mysql-service
spec:
  selector:
    name: mysql-pod   # Pod un label i yakalayacak. Servisler podlari yakalar deploymentlari degil
  ports:
    - port: 3306
      targetPort: 3306
